language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer install --dev

script:
  - ./vendor/bin/atoum -d tests/units

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly
    - php: hhvm
